### ISSUE TITLE
Minetest → Luanti rename checklist

### ISSUE THREAD

**Issue by Wuzzy2** [luanti-org/luanti#15322]
It has been decided to rename Minetest to Luanti. <https://blog.minetest.net/2024/10/13/Introducing-Our-New-Name/>

This issue is a checklist of all the places where the name needs updating.

## Done

<details>

* [x] Flathub: Resubmit as `org.luanti.luanti`, then [do the EoL rebase](https://github.com/flathub/net.minetest.Minetest/pull/74)

### Luanti application

* [x] Project name (#15294)
* [x] menu_header.png (#15294)
* [x] "ASCII" splash (#15294)
* [X] `README.md`
* [X] `doc/lua_api.md`
* [x] All other files in `doc/` (#15294)
* [x] `builtin/settingtypes.txt` (#15324)
* [x] builtin code (#15324)
* [X] DevTest
* [x] Devtest: `minetest.*` -> `core.*` (#15349)

### Minetest Game

* [x] Rename "Minetest" to "Luanti" in Minetest Game (https://github.com/minetest/minetest_game/commit/312a67b40c77395a6c1a791c1f9efaa803635925)

### Git / GitHub

* [x] "About" section of <https://github.com/minetest/minetest> (Ctrl+F "Minetest is an open source voxel game-creation platform with easy modding and game creation")

### Websites

* [x] Website domain
* [x] Website contents (https://github.com/minetest/minetest.github.io/pull/311)
* [x] Blog domain
* [x] API docs domain (api.minetest.net)
* [x] Rename Minetest Blog to Luanti Blog (https://github.com/minetest/blog/pull/155)
* [x] Update the pages of Minetest Wiki / Luanti Wiki (at least English)
* [x] Update the pages of Minetest Developer Wiki / Luanti Developer Wiki (at least English)
* [x] Mentions of "Minetest" in ContentDB

### Social media

* [X] Mastodon account
* [x] Maybe edit the pinned posts of the Mastodon account
* [X] Forums
* [x] Subforum name: "Minetest-related projects" <https://forum.minetest.net/viewforum.php?f=14>
* [x] Rename "Minetest" ContentDB user to "Luanti"
    *  minetest game and sethome packages are being left under the minetest user, assuming that they will be left in the minetest org on github.

## Semi-official

* [x] Minetest Modding Book by @rubenwardy (included in checklist because it's mentioned in `lua_api.md`)
* [x] Update Minetest [luacheck](https://github.com/lunarmodules/luacheck) standard to support `core` (https://github.com/lunarmodules/luacheck/pull/118)
    * This standard should be updated every release, but this one is particularly important since everything will start using `core` now.

</details>

## To-Do

Edit by @appgurueu: Grouped into "Done" and "To-Do", ordered To-Dos roughly by estimated descending priority.

### Package Sources

* [ ] Maybe: Create new `luantidevs` PPA, rename `minetest` to `luanti` as well, making sure to mark it as "provides `minetest`" so dependencies aren't broken

### High-risk

* [ ] Maybe rename application directories (e.g. `~/.minetest`, but it should probably be moved to `~/.local`, `~/.config`, etc. anyway in accordance with standards, e.g. XDG #15382)

### Social media

* [x] Official IRC channels (`#minetest`, `#minetest-dev`, etc.)
~~* [ ] Title and contents of sticky forum threads, see <https://forum.luanti.org/viewtopic.php?p=440359#p440359>~~ not happening, many sticky threads aren't updated, the renaming issue is just a part of the problem
* [x] Rename "Minetest" forum user to "Luanti"

### Git / GitHub

* [x] Maybe: Git repo name
* [x] Maybe: GitHub organization name

### Websites

* [x] Rename Minetest Wiki to Luanti Wiki
* [x] Rename Minetest Developer Wiki to Luanti Developer Wiki
* [x] Update the main page of Minetest Wiki / Luanti Wiki
* [x] Update the main page of Minetest Developer Wiki / Luanti Developer Wiki
* [x] Maybe project and component names on Weblate

----

## Small warning about tools

Be careful when you mass-rename "Minetest" to "Luanti" with a tool that you don’t acidentally rename Minetest Game to Luanti Game.

----

(I've checked if a similar issue already exists but found none, so I decided to post it myself.)

(moderators: feel free to edit this list when you find new places or if you disagree with a particular point)

EDIT by SmallJoker: XDG directory issue reference.

**Comment by Wuzzy2** [comment]
Note: I've un-ticked "All other files in doc/" again because there are still files in there with "Minetest", for example `minetest.6` (manpage), `main_page.dox` and others. Don't forget to search recursively.

**Comment by Wuzzy2** [comment]
After a few days of hard work, I'm very happy to announce that both wikis have pretty much all their content pages (excluding translated pages) updated to say "Luanti" instead of "Minetest", where appropriate. In places where a distinction between versions is important, I clarified that as well.

It's possible I've overlooked a small number of pages, but as I used page search extensively, so I'm positive all the important pages are now covered. I guess the missing instances will slowly get picked up by other wiki editors or me in the next years.

The only important page that is missing is the Main Page on both wikis, since I'm not allowed to edit them. Those pages still use the name "Minetest" in the text.

Also, the wikis themselves should be renamed as well to include "Luanti" in their name.

You can find more information about open wiki tasks that require admin intervention at the talk pages of both wiki Main Pages, and here: https://wiki.minetest.net/Minetest_Wiki:TODO

**Comment by superfloh247** [comment]
current latest dev build still writes screenshots to /Users/*username*/Library/Application Support/minetest/screenshots

(MacOS)

**Comment by sfence** [comment]
> current latest dev build still writes screenshots to /Users/_username_/Library/Application Support/minetest/screenshots
> 
> (MacOS)

Paths for finding games, worlds, and store screenshots have not been changed to keep Luanti backward compatible with Minetest.

**Comment by okias** [comment]
website, github repos, would be cool to be aligned with new name... I'm not sure why to announce it, when lot of assets stay with old name.

Btw. high risk (following XDG standard). That's the best thing to do now, as after renaming it's kinda expected the default name will change, so changing path is easier.

**Comment by appgurueu** [comment]
> website, github repos, would be cool to be aligned with new name...

I agree, but one thing at a time. Right now the priority is to rename everything that's directly using-facing. The application has already largely been renamed, as well as the website (as of yesterday, https://luanti.org also works), which is good, now we have to rename the blog etc.

> I'm not sure why to announce it, when lot of assets stay with old name.

The announcement lets us rename gradually in the open. Otherwise it would be rather confusing if we just started renaming things visibly and *only then* announced that we are going to rename (and what we are renaming to).
It is common for announcements to precede action.

**Comment by okias** [comment]
The website is great, that was one of the first thing I hit when I tried to rename the package (as I had to point to old website).

Usually the renaming (at least what I saw before) goes thou in one batch, so it's announcement and all the MR/PR got merged, so it's close to instantly flipped to avoid confusion. Anyway, thank you, with the website it's much better experience now :)

**Comment by appgurueu** [comment]
Many of the remaining points on the checklist require @celeron55 to resolve them:

- [ ] Blog domain
- [ ] API docs domain (api.minetest.net)
- [ ] Rename Minetest Wiki to Luanti Wiki
- [ ] Rename Minetest Developer Wiki to Luanti Developer Wiki
- [ ] Update the main page of Minetest Wiki / Luanti Wiki
- [ ] Update the main page of Minetest Developer Wiki / Luanti Developer Wiki

luckily these should all be pretty easy for celeron to resolve.

**Comment by o1101o** [comment]
Hey what's up y'all. I was thinking about making a Luanti FB Page if that's ok? I've heard y'all don't really care about Social Media, but wanted to make sure it was Ok anyway. 
Of course I'm a huge fan. I've got Luanti/ Minetest installed on Windows 10, 11, Androids and Linux Mint. Been playing it a couple years now. My 11 year old son builds his own games.

**Comment by appgurueu** [comment]
> Hey what's up y'all. I was thinking about making a Luanti FB Page if that's ok? I've heard y'all don't really care about Social Media, but wanted to make sure it was Ok anyway. Of course I'm a huge fan. I've got Luanti/ Minetest installed on Windows 10, 11, Androids and Linux Mint. Been playing it a couple years now. My 11 year old son builds his own games.

We are present to some extent on some platforms, but not on Facebook. An unofficial Luanti Facebook page should certainly be fine. If it gains a certain amount of traction and aligns with our values, there even is a chance that it might eventually be made official (that's what happened with the Discord, for example).

**Comment by o1101o** [comment]
Awesome. 
I created the Luanti FB page.
https://www.facebook.com/profile.php?id=61569556196555

Btw, my name's Chris Arthur and I'm based out of New Orleans. I'm an Entry-Level IT Specialist, Teacher, Writer and Revolutionary. Luanti... is... Revolutionary. That's why I'm here.
My hope is to promote/ continue promoting Luanti through Education. I've been planting seeds through emails, resumes and interactions with educational faculty and Administrators.
I'm pretty good with tech, but many teachers and most parents aren't.....

Which brings me to my One Request:
Would it be possible to put in a request for a Luanti Game?

It would be pretty awesome to have a "School" Game. I usually program my School/Education-oriented Games with:
-Periodic Table of Elements -Math Blocks -All Phonics -Alphabet -Dreambuilder Hotbar Extender -Crafting table/ Guide/ Books/ Encyclopedia -Teacher/ Classroom -Journal -Laptop/ Extended Laptop/ Computer -Travelnet -Flight -Sandwiches 
-Real Time -Map/ Compass -Bouncing Bed -Balloon Blocks -Multidimensions -School Furniture -Unified Inventory/Blocks/Etc
-Tsalagi Letters/ Japanese Letters -Beacon -Bells/Church Bells -Board/ Chalkboard/ Whiteboard?/Signs -3Darmor

One thing I'd like to avoid are Mobs, for distraction purposes.
As far as Houses, Villages, Biomes, Sounds, Weather, Settings and all that goes I'll leave that up to y'all. I do really like Multidimensions. It allows for easy building and incorporation of Layered Education.  They can be separated into Separate Subjects, Advancing Layers of 1, single Subject or even separated by Grade Levels. 

Well, that's it for now. I'm off to work. Thanks for making the best game in the world. :)

**Comment by Hellscaped** [comment]
> Awesome. I created the Luanti FB page. https://www.facebook.com/profile.php?id=61569556196555
> 
> Btw, my name's Chris Arthur and I'm based out of New Orleans. I'm an Entry-Level IT Specialist, Teacher, Writer and Revolutionary. Luanti... is... Revolutionary. That's why I'm here. My hope is to promote/ continue promoting Luanti through Education. I've been planting seeds through emails, resumes and interactions with educational faculty and Administrators. I'm pretty good with tech, but many teachers and most parents aren't.....
> 
> Which brings me to my One Request: Would it be possible to put in a request for a Luanti Game?
> 
> It would be pretty awesome to have a "School" Game. I usually program my School/Education-oriented Games with: -Periodic Table of Elements -Math Blocks -All Phonics -Alphabet -Dreambuilder Hotbar Extender -Crafting table/ Guide/ Books/ Encyclopedia -Teacher/ Classroom -Journal -Laptop/ Extended Laptop/ Computer -Travelnet -Flight -Sandwiches -Real Time -Map/ Compass -Bouncing Bed -Balloon Blocks -Multidimensions -School Furniture -Unified Inventory/Blocks/Etc -Tsalagi Letters/ Japanese Letters -Beacon -Bells/Church Bells -Board/ Chalkboard/ Whiteboard?/Signs -3Darmor
> 
> One thing I'd like to avoid are Mobs, for distraction purposes. As far as Houses, Villages, Biomes, Sounds, Weather, Settings and all that goes I'll leave that up to y'all. I do really like Multidimensions. It allows for easy building and incorporation of Layered Education. They can be separated into Separate Subjects, Advancing Layers of 1, single Subject or even separated by Grade Levels.
> 
> Well, that's it for now. I'm off to work. Thanks for making the best game in the world. :)

Wrong place, the forums would be better for a game request

**Comment by celeron55** [comment]
I added blog.luanti.org and api.luanti.org DNS now. They're the same as for the corresponding minetest.net ones, which is, CNAME to minetest.github.io. This obviously means someone has to configure the github pages for each accordingly.

**Comment by celeron55** [comment]
I now set up a redirect for the wiki also, and renamed it (the title now has a different name).

However, it's not simple to fully rename it. For example, should I change the metapage prefix which is currently Minetest_Wiki? This will affect links like https://wiki.luanti.org/Minetest_Wiki:About

**Comment by Wuzzy2** [comment]
Yes, please rename the "Minetest Wiki:" namespace, too. I will do the neccessary cleanup afterwards. There are not *that* many pages in that namespace anyway, so it should be fine.

Also, the main page and logo still needs updating. And all of that applies to the dev wiki as well.

**Comment by Wuzzy2** [comment]
The renaming/rewriting of sticky forum threads was rejected on the grounds of "many sticky threads are not updated".

Well, if these threads are outdated anyway, just unsticky them (any notify the author to give them a chance to update). It's not good when the forum is full of sticky but outdated forum threads. I also feel many sticky threads would work better as wiki pages.

Are sticky threads considered "holy"? I.e. once written, they must never be touched again?

**Comment by omicron1100** [comment]
Are `minetest.conf` and `minetest.conf.example` being changed to `luanti.conf` and `luanti.conf.example`?

**Comment by sfence** [comment]
> Are `minetest.conf` and `minetest.conf.example` being changed to `luanti.conf` and `luanti.conf.example`?

Probably not, because of backward compatibility.

**Comment by okias** [comment]
> > Are `minetest.conf` and `minetest.conf.example` being changed to `luanti.conf` and `luanti.conf.example`?
> 
> Probably not, because of backward compatibility.

you can easily create new `luanti.conf` and if it doesn't exist, fall back to old name config.

**Comment by Wuzzy2** [comment]
The renaming checklist is almost complete. There are only 3 remaining things on the list, and two of them are "maybes":

1. Flathub: Resubmit as org.luanti.luanti, then https://github.com/flathub/net.minetest.Minetest/pull/74
2. Maybe: Create new luantidevs PPA, rename minetest to luanti as well, making sure to mark it as "provides minetest" so dependencies aren't broken
3. Maybe rename application directories (e.g. ~/.minetest, but it should probably be moved to ~/.local, ~/.config, etc. anyway in accordance with standards, e.g. XDG https://github.com/luanti-org/luanti/issues/15382)

A decision should be made about the "maybes"; I think it is valid to decide to leave things as-is for those maybes and thus remove them from the checklist.
I'm not sure if those 3 things are really neccessary because it seems this concerns only internal naming stuff and seem rather esoteric. If it’s not user-facing text, it is irrelevant to this issue. IMHO those would better be rejected, or moved to individual issues.

I’m not sure if Flathub rename is really neccessary, as this only concerns an internal name, right? And as far I know, many projects reside there with their old (internal) name to keep things simple and this seems to be standard practice. (I may be misremembering tho)
I have no idea what the "luantidevs PPA" is about. Some internal Debian repo stuff?
And about XDG: An official decision should be made whether we rename `.minetest` directory to `.luanti`, or go straight to XDG or if we intentionally leave things as-is. I strongly prefer XDG, because I am also annoyed by all those applications pulluting my home directory with billions of "dot" directories. If this directory is going to be renamed anyway, better do it right the first time.

**Comment by appgurueu** [comment]
1. The Flathub resubmission has come through, now we just gotta do the EOL rebase.
2. I don't care terribly much at the moment. Arguably PPA names and package names are user-facing though. Additionally I think a fresh PPA would pose a good opportunity to have a less crufty Launchpad setup. But this is low-priority, it works at the moment and I'm afraid of touching it.
3. I think XDG is the way to go. See also: #16092.

I think we can essentially close this issue, especially as there's a separate issue for XDG. Opinions?

**Comment by appgurueu** [comment]
The EOL rebase has come through. Closing.
