### ISSUE TITLE
Client-side API sandboxing

### ISSUE THREAD

**Issue by red-001** [luanti-org/luanti#7041]
##### Summary
Issue for tracking the state of CSM sandboxing

##### TODO List

- [x] Block direct access to filesystem, only letting Lua to access a VFS. (#5965)
- [x] Don't load the IO library. (#6087)
- [x] Don't load the package library. (#6944)
- [x] Don't allow access to the debug library.
- [x] Only allow access to safe functions in the OS library.
- [ ] Limit how much data can be stored in mod storage.
- [ ] Don't allow CSM to mess around with the pause/escape menu (e.g. closing/overriding or otherwise interfering with it).
- [ ] Don't load the OS library at all, and replicate the time related functions in it that mods might need.
- [ ] Disable LuaJIT and JIT compiling
- [ ] Seperate mods into their own `lua_state`'s and block access to certain functions unless the mod receives permission from the user (e.g. screenshot api)?
- [ ] Put environment into a jail? ( https://github.com/mniip/sandbox/ )

**Comment by raymoo** [comment]
What about have mods be able to expose functions to each other in some way?

**Comment by red-001** [comment]
@raymoo mod channels could be modified to also allow inter-mod communication if the last point ends up being implemented.

**Comment by raymoo** [comment]
@red-001 Why is it necessary to have separate states instead of just share a state and use different environments for each mod's client code? Then you could include a table that's shared between all the environments where mods could put things they want to share.

**Comment by sfan5** [comment]
IMO client mods should definitely all run in separate states.
Doing this vastly reduces the attack surface of one mod tricking another mod into exposing "protected" functions (comparable to the server-side `request_insecure_environment()`).

**Comment by raymoo** [comment]
@sfan5 That makes sense, but it's unfortunate that every mod using an API exposed by another mod would need to include its own wrappers for the message passing (or just mess around with channels directly everywhere).

It would be less of a problem if there were more efficient ways to serialize data from mod code. I don't know if there's some kind of serialization library that could be included in the CSM API.

**Comment by raymoo** [comment]
I did some asking around and there is this: http://www.inf.puc-rio.br/~roberto/struct/

In Lua 5.3 it would be in the standard library.

**Comment by sfan5** [comment]
If it's for communication between client-side mods, you can just have a method that recursively copies objects (and their contents) from one state to another. No serialization needed.

**Comment by raymoo** [comment]
@sfan5 Sounds good to me, as long as the mod will be able to handle it similarly to mod channel messages. It would be bad if the data had to be copied somewhere and then the receiving mod notified separately that it needed to check the data.

**Comment by sfan5** [comment]
Questions that also have to be considered:
* Do you want to "crash" the whole client when a Lua error occurs?
* How do you prevent mods from locking up the client? (intentionally or unintentionally)

**Comment by raymoo** [comment]
A limitation of the copying approach above that I guess I forgot to mention before is that you couldn't copy functions, e.g. to register some callbacks to run on a hook.

**Comment by ExeVirus** [comment]
> Disable LuaJIT and JIT compiling

This has no relevance to safety as long as we restrict all server sent code to being .lua text files. luaJIT is used commercially by Cloudfare, Cisco, most game companies, etc. Mike Pall (main developer of luaJIT for last 15 years) has explained in the FAQ page that making LUA secure its nearly impossible, let alone luaJIT, though both share the exact same issues of CPU exhaustion: http://luajit.org/faq.html (halfway down)

Here is a good list of functions from Lua 5.1 that are considered safe, when starting with an empty lua environment: 
http://lua-users.org/wiki/SandBoxes

Limiting data usage is possible (i.e. restrict to 200 MB or something), and we only need to have each Server provided script have a single shared lua state, sandboxing individual Server provided scripts gains nothing in terms of security. To restrict data usage we just overwrite the default memory allocator function used by the lua state: 
https://stackoverflow.com/questions/9671793/limiting-a-lua-scripts-memory-usage

Jailing beyond these restrictions should not be needed, as we won't be exposing OS or IO libraries directly.

The only thing left after all this is to detail what kind of functions we DO want to expose. Timing is one that has been suggested, what else? 

For example, I personally would like to be able to send lua code for a client to run their own physics no each server step to overwrite the default input responses.

**Comment by TurkeyMcMac** [comment]
I'm pretty sure you can limit the number of instructions executed using `lua_sethook`, but only if you turn the JIT off. This technique is used by Mesecons LuaControllers.

One option would be to start a separate process and do all the server-sent client-side scripting on that process. This would allow for the use of process-level sandboxing where available.

**Comment by aerkiaga** [comment]
[Here](http://lua-users.org/wiki/SandBoxes) is a useful document on sandboxing Lua code. It contains an exhaustive list of safe and unsafe members in the standard library.

**Comment by aerkiaga** [comment]
I'd suggest hiding or reimplementing (as wrappers) unsafe/inadequate functions while still loading the libraries. That seems simpler than adding a new API.

**Comment by red-001** [comment]
Closing this since CSM seems basically dead for now, hopefully SSCSM will avoid becoming a similar API that's never to be actually shipped. I think the points about disabling JIT are probably still relevant, as is the OS level sandboxing but this can be discussed in new issues that actually account for the new framework being proposed.
